spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/orders
    username: orders_user
    password: orders_pass
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.batch_size: 1000
      hibernate.order_inserts: true
      hibernate.order_updates: true
  flyway:
    enabled: true
  batch:
    jdbc:
      initialize-schema: always

app:
  io:
    inputPattern: "/data/in/orders_{dataDate}.csv"
    aggregatesPattern: "/data/out/{dataDate}/aggregates.csv"
    rejectsPattern: "/data/out/{dataDate}/rejects.csv"
  schedule:
    cron: "0 0 20 * * *"
  timezone: "Asia/Singapore"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
