from __future__ import annotations

from enum import Enum


class Side(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class EventType(str, Enum):
    ALLOCATED_BUY_PENDING = "ALLOCATED_BUY_PENDING"
    ALLOCATED_SELL_PENDING = "ALLOCATED_SELL_PENDING"
    SETTLED_BUY_ATTRIBUTED = "SETTLED_BUY_ATTRIBUTED"
    SETTLED_SELL_ATTRIBUTED = "SETTLED_SELL_ATTRIBUTED"
    PENDING_BUY_REVERSED = "PENDING_BUY_REVERSED"
    PENDING_SELL_REVERSED = "PENDING_SELL_REVERSED"
    MANUAL_ADJUSTMENT = "MANUAL_ADJUSTMENT"
    EXTERNAL_ADJUSTMENT = "EXTERNAL_ADJUSTMENT"
    CUSTODY_CONTROL_TOTAL_RECEIVED = "CUSTODY_CONTROL_TOTAL_RECEIVED"


class EventStatus(str, Enum):
    OPEN = "OPEN"
    SETTLED = "SETTLED"
    REVERSED = "REVERSED"


class ExceptionType(str, Enum):
    RECON_MISMATCH = "RECON_MISMATCH"


UNKNOWN_PLACE_OF_TRADE = "UNKNOWN"
